### ISSUE TITLE
Reading?

### ISSUE THREAD

**Issue by s6carlo** [enjoping/DXFighter#1]
Any news about DXF reading? 
In our application we should write simple form but we have to import inside them a given DXF.

For example draw a rectangle and import at the center of it a form taken from another DXF file, with a specific scale factor.

**Comment by enjoping** [comment]
Hey,

thank you for your interest in DXFighter. I'm currently actively developing the reader and estimate it to be finished within next weak. I hope to have a first working version within this weekend. I'll inform you as soon as something to test is ready.

**Comment by enjoping** [comment]
Hey,

I've finished a first version of the reader and pushed it to the master branch. I didn't update the documentation by now but you will find an example in the example.php file in the repository. If you encounter problems please just open a new issue.
