### ISSUE TITLE
Can I add a dxf into another dxf

### ISSUE THREAD

**Issue by dannyng1988** [enjoping/DXFighter#3]
I have a icon in dxf format, now I want to read this icon into my program and create a new dxf with this tool. Please look at the link below. I will draw the squares with your tool, for the icons, we already have them in dxf format, so I decieded to import them.

https://autode.sk/3aOjl0R

**Comment by enjoping** [comment]
Hey Danny,

I'm happy to see your interest in DXFighter. Sure you are able using the tool to import DXF files and edit / extend them. DXFighter is indeed able to read some DXF files but I'm happy to extend the functionality using your example. But in theory your use case should work using our library.
As I've seen I have an email from you so I guess it's best to discuss the details of what changes you may need there. Therefore I will close the ticket but you will hear from me later today.

Greetings Joe
